# Generated by Django 5.1.1 on 2024-10-01 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barcode_info',
            fields=[
                ('barcode_structr', models.CharField(default='EAN-13', max_length=100, primary_key=True, serialize=False)),
                ('barcode_num', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('product_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('product_img', models.BinaryField(blank=True, null=True)),
                ('product_memo', models.TextField(blank=True, null=True)),
                ('product_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('storage_retrieval', models.CharField(choices=[('출고', '출고'), ('입고', '입고')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=128)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=15)),
                ('sign_up_day', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
