# Generated by Django 5.1.1 on 2024-11-14 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="product_info",
            fields=[
                (
                    "barcode_num",
                    models.CharField(
                        default="0000000000000",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("product_name", models.CharField(max_length=100, null=True)),
                ("classification", models.CharField(max_length=100, null=True)),
                ("initial_stock", models.IntegerField(null=True)),
                ("current_quantity", models.IntegerField(null=True)),
                (
                    "product_image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("product_memo", models.TextField(blank=True, null=True)),
                (
                    "barcode_structure",
                    models.CharField(default="EAN-13", max_length=100),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.user_info",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("barcode_num", "user_id"), name="superkey_productInfo"
                    )
                ],
            },
        ),
    ]
