# Generated by Django 5.1.1 on 2024-10-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '__first__'),
        ('scannerApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='barcode_info',
        ),
        migrations.DeleteModel(
            name='product_log',
        ),
        migrations.DeleteModel(
            name='user_info',
        ),
        migrations.AddField(
            model_name='product_info',
            name='barcode_num',
            field=models.CharField(default='0000000000000', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='product_info',
            name='barcode_structr',
            field=models.CharField(default='EAN-13', max_length=100),
        ),
        migrations.AddField(
            model_name='product_info',
            name='userInfo_id',
            field=models.OneToOneField(default='유저아이디', on_delete=django.db.models.deletion.CASCADE, to='mainApp.user_info'),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='product_info',
            constraint=models.UniqueConstraint(fields=('barcode_num', 'userInfo_id'), name='superkey_productInfo'),
        ),
    ]
