# Generated by Django 5.1.1 on 2024-09-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannerApp', '0002_barcode_info_barcode_structr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode_info',
            name='barcode_num',
            field=models.BigIntegerField(),
        ),
    ]
