# Generated by Django 5.1.1 on 2024-12-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scannerApp', '0002_rename_barcode_structure_product_info_barcode_structr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_info',
            old_name='barcode_structr',
            new_name='barcode_structer',
        ),
    ]
