# Generated by Django 5.1.1 on 2024-10-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scannerApp", "0002_alter_product_info_userinfo_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product_info",
            old_name="barcode_structr",
            new_name="barcode_structure",
        ),
    ]
