# Generated by Django 5.1.1 on 2024-09-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannerApp', '0003_alter_barcode_info_barcode_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode_info',
            name='barcode_num',
            field=models.CharField(default='0000000000000', max_length=100),
        ),
    ]
