# Generated by Django 5.1.1 on 2024-10-14 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
        ("scannerApp", "0003_rename_barcode_structr_product_info_barcode_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_info",
            name="userInfo_id",
            field=models.ForeignKey(
                db_column="userInfo_id",
                default="유저아이디",
                on_delete=django.db.models.deletion.CASCADE,
                to="mainApp.user_info",
            ),
        ),
    ]
