# Generated by Django 5.1.1 on 2024-09-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannerApp', '0004_alter_barcode_info_barcode_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(default='분류없음', max_length=100)),
                ('product_name', models.CharField(default='상품명없음', max_length=100)),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_image', models.BinaryField(blank=True, null=True)),
                ('product_memo', models.TextField(default='메모없음')),
            ],
        ),
    ]
