# Generated by Django 5.1.1 on 2024-11-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
        ("scannerApp", "0004_alter_product_info_userinfo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_info",
            name="barcode_structure",
            field=models.CharField(default="EAN-13", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product_info",
            name="classification",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product_info",
            name="product_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product_info",
            name="product_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product_info",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product_info",
            name="userInfo_id",
            field=models.ForeignKey(
                db_column="userInfo_id",
                default="유저아이디",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainApp.user_info",
            ),
        ),
    ]
