# Generated by Django 5.1.1 on 2024-10-04 17:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '__first__'),
        ('scannerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_log',
            fields=[
                ('change_quantity', models.IntegerField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, unique=True)),
                ('storage_retrieval', models.CharField(choices=[('출고', '출고'), ('입고', '입고')], max_length=2, primary_key=True, serialize=False)),
                ('productInfo_barcodeNum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scannerApp.product_info')),
                ('userInfo_id', models.OneToOneField(default='유저아이디', on_delete=django.db.models.deletion.CASCADE, to='mainApp.user_info')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date_time', 'userInfo_id', 'productInfo_barcodeNum'), name='superkey_productLog')],
            },
        ),
    ]
