# Generated by Django 5.1.1 on 2024-11-14 03:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mainApp", "0001_initial"),
        ("scannerApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="product_log",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("change_quantity", models.IntegerField(null=True)),
                ("date_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "storage_retrieval",
                    models.CharField(
                        choices=[("출고", "출고"), ("입고", "입고")], max_length=2
                    ),
                ),
                (
                    "productInfo_barcodeNum",
                    models.ForeignKey(
                        db_column="productInfo_barcodeNum",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scannerApp.product_info",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.user_info",
                    ),
                ),
            ],
        ),
    ]
