# Generated by Django 5.1.1 on 2024-10-04 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryflowApp', '0001_initial'),
        ('mainApp', '0001_initial'),
        ('scannerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_log',
            name='productInfo_barcodeNum',
            field=models.OneToOneField(db_column='productInfo_barcodeNum', on_delete=django.db.models.deletion.CASCADE, to='scannerApp.product_info'),
        ),
        migrations.AlterField(
            model_name='product_log',
            name='userInfo_id',
            field=models.OneToOneField(db_column='userInfo_id', default='유저아이디', on_delete=django.db.models.deletion.CASCADE, to='mainApp.user_info'),
        ),
    ]
